##### Copyright 2019 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Classify structured data with feature columns

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/structured_data/feature_columns">
    <img src="https://www.tensorflow.org/images/tf_logo_32px.png" />
    View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://www.tensorflow.org/images/colab_logo_32px.png" />
    Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />
    View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/structured_data/feature_columns.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

> Warning: The `tf.feature_columns` module described in this tutorial is not recommended for new code. [Keras preprocessing layers](https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers) cover this functionality, for migration instructions see the [Migrating feature columns](../../guide/migrate/migrating_feature_columns.ipynb) guide. The `tf.feature_columns` module was designed for use with TF1 `Estimators`. It does fall under our [compatibility guarantees](https://tensorflow.org/guide/versions), but will receive no fixes other than security vulnerabilities.

This tutorial demonstrates how to classify structured data (e.g. tabular data in a CSV). We will use [Keras](https://www.tensorflow.org/guide/keras) to define the model, and `tf.feature_column` as a bridge to map from columns in a CSV to features used to train the model. This tutorial contains complete code to:

* Load a CSV file using [Pandas](https://pandas.pydata.org/).
* Build an input pipeline to batch and shuffle the rows using [tf.data](https://www.tensorflow.org/guide/datasets).
* Map from columns in the CSV to features used to train the model using feature columns.
* Build, train, and evaluate a model using Keras.

## The Dataset

We will use a simplified version of the PetFinder [dataset](https://www.kaggle.com/c/petfinder-adoption-prediction). There are several thousand rows in the CSV. Each row describes a pet, and each column describes an attribute. We will use this information to predict the speed at which the pet will be adopted.

Following is a description of this dataset. Notice there are both numeric and categorical columns. There is a free text column which we will not use in this tutorial.

Column | Description| Feature Type | Data Type
------------|--------------------|----------------------|-----------------
Type | Type of animal (Dog, Cat) | Categorical | string
Age |  Age of the pet | Numerical | integer
Breed1 | Primary breed of the pet | Categorical | string
Color1 | Color 1 of pet | Categorical | string
Color2 | Color 2 of pet | Categorical | string
MaturitySize | Size at maturity | Categorical | string
FurLength | Fur length | Categorical | string
Vaccinated | Pet has been vaccinated | Categorical | string
Sterilized | Pet has been sterilized | Categorical | string
Health | Health Condition | Categorical | string
Fee | Adoption Fee | Numerical | integer
Description | Profile write-up for this pet | Text | string
PhotoAmt | Total uploaded photos for this pet | Numerical | integer
AdoptionSpeed | Speed of adoption | Classification | integer

## Import TensorFlow and other libraries

In [2]:
!pip install sklearn

  Preparing metadata (setup.py) ... -

 done


 \ done
  Created wheel for sklearn: filename=sklearn-0.0.post10-py3-none-any.whl size=2959 sha256=39c24f8be536daf36c3f540edffc9a5ce223991c9de1531dbfd582e057aaea25
  Stored in directory: /home/kbuilder/.cache/pip/wheels/59/9c/1b/6be8fc606a34b098ddb96d3d5e07fb21d49599055fa0c0fe87
Successfully built sklearn


In [3]:
import numpy as np
import pandas as pd

import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

2023-10-27 05:23:51.727166: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-27 05:23:51.727210: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-27 05:23:51.728742: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


## Use Pandas to create a dataframe

[Pandas](https://pandas.pydata.org/) is a Python library with many helpful utilities for loading and working with structured data. We will use Pandas to download the dataset from a URL, and load it into a dataframe.

In [4]:
import pathlib

dataset_url = 'http://storage.googleapis.com/download.tensorflow.org/data/petfinder-mini.zip'
csv_file = 'datasets/petfinder-mini/petfinder-mini.csv'

tf.keras.utils.get_file('petfinder_mini.zip', dataset_url,
                        extract=True, cache_dir='.')
dataframe = pd.read_csv(csv_file)

   8192/1668792 [..............................] - ETA: 0s

1668792/1668792 [==============================] - 0s 0us/step


In [5]:
dataframe.head()

Type  Age                Breed1  Gender Color1    Color2 MaturitySize  \
0  Cat    3                 Tabby    Male  Black     White        Small   
1  Cat    1  Domestic Medium Hair    Male  Black     Brown       Medium   
2  Dog    1           Mixed Breed    Male  Brown     White       Medium   
3  Dog    4           Mixed Breed  Female  Black     Brown       Medium   
4  Dog    1           Mixed Breed    Male  Black  No Color       Medium   

  FurLength Vaccinated Sterilized   Health  Fee  \
0     Short         No         No  Healthy  100   
1    Medium   Not Sure   Not Sure  Healthy    0   
2    Medium        Yes         No  Healthy    0   
3     Short        Yes         No  Healthy  150   
4     Short         No         No  Healthy    0   

                                         Description  PhotoAmt  AdoptionSpeed  
0  Nibble is a 3+ month old ball of cuteness. He ...         1              2  
1  I just found it alone yesterday near my apartm...         2              0  
2  Their pregnant mother was dumped by her irresp...         7              3  
3  Good guard dog, very alert, active, obedience ...         8              2  
4  This handsome yet cute boy is up for adoption....         3              2

## Create target variable

The task in the original dataset is to predict the speed at which a pet will be adopted (e.g., in the first week, the first month, the first three months, and so on). Let's simplify this for our tutorial. Here, we will transform this into a binary classification problem, and simply predict whether the pet was adopted, or not.

After modifying the label column, 0 will indicate the pet was not adopted, and 1 will indicate it was.

In [6]:
# In the original dataset "4" indicates the pet was not adopted.
dataframe['target'] = np.where(dataframe['AdoptionSpeed']==4, 0, 1)

# Drop un-used columns.
dataframe = dataframe.drop(columns=['AdoptionSpeed', 'Description'])

## Split the dataframe into train, validation, and test

The dataset we downloaded was a single CSV file. We will split this into train, validation, and test sets.

In [7]:
train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

7383 train examples
1846 validation examples
2308 test examples


## Create an input pipeline using tf.data

Next, we will wrap the dataframes with [tf.data](https://www.tensorflow.org/guide/datasets). This will enable us  to use feature columns as a bridge to map from the columns in the Pandas dataframe to features used to train the model. If we were working with a very large CSV file (so large that it does not fit into memory), we would use tf.data to read it from disk directly. That is not covered in this tutorial.

In [8]:
# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [9]:
batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## Understand the input pipeline

Now that we have created the input pipeline, let's call it to see the format of the data it returns. We have used a small batch size to keep the output readable.

In [10]:
for feature_batch, label_batch in train_ds.take(1):
  print('Every feature:', list(feature_batch.keys()))
  print('A batch of ages:', feature_batch['Age'])
  print('A batch of targets:', label_batch )

Every feature: ['Type', 'Age', 'Breed1', 'Gender', 'Color1', 'Color2', 'MaturitySize', 'FurLength', 'Vaccinated', 'Sterilized', 'Health', 'Fee', 'PhotoAmt']
A batch of ages: tf.Tensor([ 2 24  1  4  2], shape=(5,), dtype=int64)
A batch of targets: tf.Tensor([1 1 1 1 1], shape=(5,), dtype=int64)


We can see that the dataset returns a dictionary of column names (from the dataframe) that map to column values from rows in the dataframe.

## Demonstrate several types of feature columns
TensorFlow provides many types of feature columns. In this section, we will create several types of feature columns, and demonstrate how they transform a column from the dataframe.

In [11]:
# We will use this batch to demonstrate several types of feature columns
example_batch = next(iter(train_ds))[0]

In [12]:
# A utility method to create a feature column
# and to transform a batch of data
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

### Numeric columns
The output of a feature column becomes the input to the model (using the demo function defined above, we will be able to see exactly how each column from the dataframe is transformed). A [numeric column](https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column) is the simplest type of column. It is used to represent real valued features. When using this column, your model will receive the column value from the dataframe unchanged.

In [13]:
photo_count = feature_column.numeric_column('PhotoAmt')
demo(photo_count)

Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.


[[2.]
 [1.]
 [2.]
 [3.]
 [1.]]


In the PetFinder dataset, most columns from the dataframe are categorical.

### Bucketized columns
Often, you don't want to feed a number directly into the model, but instead split its value into different categories based on numerical ranges. Consider raw data that represents a person's age. Instead of representing age as a numeric column, we could split the age into several buckets using a [bucketized column](https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column). Notice the one-hot values below describe which age range each row matches.

In [14]:
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 3, 5])
demo(age_buckets)

Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.


[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


### Categorical columns
In this dataset, Type is represented as a string (e.g. 'Dog', or 'Cat'). We cannot feed strings directly to a model. Instead, we must first map them to numeric values. The categorical vocabulary columns provide a way to represent strings as a one-hot vector (much like you have seen above with age buckets). The vocabulary can be passed as a list using [categorical_column_with_vocabulary_list](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_list), or loaded from a file using [categorical_column_with_vocabulary_file](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file).

In [15]:
animal_type = feature_column.categorical_column_with_vocabulary_list(
      'Type', ['Cat', 'Dog'])

animal_type_one_hot = feature_column.indicator_column(animal_type)
demo(animal_type_one_hot)

Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.


Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.


[[0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


### Embedding columns
Suppose instead of having just a few possible strings, we have thousands (or more) values per category. For a number of reasons, as the number of categories grow large, it becomes infeasible to train a neural network using one-hot encodings. We can use an embedding column to overcome this limitation. Instead of representing the data as a one-hot vector of many dimensions, an [embedding column](https://www.tensorflow.org/api_docs/python/tf/feature_column/embedding_column) represents that data as a lower-dimensional, dense vector in which each cell can contain any number, not just 0 or 1. The size of the embedding (8, in the example below) is a parameter that must be tuned.

Key point: using an embedding column is best when a categorical column has many possible values. We are using one here for demonstration purposes, so you have a complete example you can modify for a different dataset in the future.

In [16]:
# Notice the input to the embedding column is the categorical column
# we previously created
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
demo(breed1_embedding)

Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.


[[ 0.23340847 -0.22288084  0.41993982  0.48253137  0.14740573 -0.30386004
   0.30413502  0.14656945]
 [-0.23076059 -0.13627627 -0.05317891  0.6952521   0.46279088 -0.5734566
  -0.04382351 -0.5681491 ]
 [ 0.45319527  0.40937862 -0.21215594  0.4152906  -0.11821023 -0.20306908
   0.31819987 -0.0359318 ]
 [-0.23076059 -0.13627627 -0.05317891  0.6952521   0.46279088 -0.5734566
  -0.04382351 -0.5681491 ]
 [-0.23076059 -0.13627627 -0.05317891  0.6952521   0.46279088 -0.5734566
  -0.04382351 -0.5681491 ]]


### Hashed feature columns

Another way to represent a categorical column with a large number of values is to use a [categorical_column_with_hash_bucket](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_hash_bucket). This feature column calculates a hash value of the input, then selects one of the `hash_bucket_size` buckets to encode a string. When using this column, you do not need to provide the vocabulary, and you can choose to make the number of hash_buckets significantly smaller than the number of actual categories to save space.

Key point: An important downside of this technique is that there may be collisions in which different strings are mapped to the same bucket. In practice, this can work well for some datasets regardless.

In [17]:
breed1_hashed = feature_column.categorical_column_with_hash_bucket(
      'Breed1', hash_bucket_size=10)
demo(feature_column.indicator_column(breed1_hashed))

Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.


[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### Crossed feature columns
Combining features into a single feature, better known as [feature crosses](https://developers.google.com/machine-learning/glossary/#feature_cross), enables a model to learn separate weights for each combination of features. Here, we will create a new feature that is the cross of Age and Type. Note that `crossed_column` does not build the full table of all possible combinations (which could be very large). Instead, it is backed by a `hashed_column`, so you can choose how large the table is.

In [18]:
crossed_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=10)
demo(feature_column.indicator_column(crossed_feature))

Instructions for updating:
Use `tf.keras.layers.experimental.preprocessing.HashedCrossing` instead for feature crossing when preprocessing data to train a Keras model.


[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Choose which columns to use
We have seen how to use several types of feature columns. Now we will use them to train a model. The goal of this tutorial is to show you the complete code (e.g. mechanics) needed to work with feature columns. We have selected a few columns to train our model below arbitrarily.

Key point: If your aim is to build an accurate model, try a larger dataset of your own, and think carefully about which features are the most meaningful to include, and how they should be represented.

In [19]:
feature_columns = []

# numeric cols
for header in ['PhotoAmt', 'Fee', 'Age']:
  feature_columns.append(feature_column.numeric_column(header))

In [20]:
# bucketized cols
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 2, 3, 4, 5])
feature_columns.append(age_buckets)

In [21]:
# indicator_columns
indicator_column_names = ['Type', 'Color1', 'Color2', 'Gender', 'MaturitySize',
                          'FurLength', 'Vaccinated', 'Sterilized', 'Health']
for col_name in indicator_column_names:
  categorical_column = feature_column.categorical_column_with_vocabulary_list(
      col_name, dataframe[col_name].unique())
  indicator_column = feature_column.indicator_column(categorical_column)
  feature_columns.append(indicator_column)

In [22]:
# embedding columns
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
feature_columns.append(breed1_embedding)

In [23]:
# crossed columns
age_type_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=100)
feature_columns.append(feature_column.indicator_column(age_type_feature))

### Create a feature layer
Now that we have defined our feature columns, we will use a [DenseFeatures](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/DenseFeatures) layer to input them to our Keras model.

In [24]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

Earlier, we used a small batch size to demonstrate how feature columns worked. We create a new input pipeline with a larger batch size.

In [25]:
batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## Create, compile, and train the model

In [26]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dropout(.1),
  layers.Dense(1)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(train_ds,
          validation_data=val_ds,
          epochs=10)

Epoch 1/10


I0000 00:00:1698384239.823402  443010 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


  1/231 [..............................] - ETA: 13:17 - loss: 0.7442 - accuracy: 0.3438

  2/231 [..............................] - ETA: 35s - loss: 0.8773 - accuracy: 0.3281  

  3/231 [..............................] - ETA: 34s - loss: 1.0630 - accuracy: 0.3229

  5/231 [..............................] - ETA: 26s - loss: 0.9441 - accuracy: 0.3438

  6/231 [..............................] - ETA: 27s - loss: 0.8938 - accuracy: 0.3802

 11/231 [>.............................] - ETA: 17s - loss: 0.7744 - accuracy: 0.5000

 12/231 [>.............................] - ETA: 18s - loss: 0.7577 - accuracy: 0.5208

 20/231 [=>............................] - ETA: 11s - loss: 0.7459 - accuracy: 0.5875

 21/231 [=>............................] - ETA: 12s - loss: 0.7347 - accuracy: 0.5982

 22/231 [=>............................] - ETA: 12s - loss: 0.7485 - accuracy: 0.6009

 29/231 [==>...........................] - ETA: 9s - loss: 0.7268 - accuracy: 0.6261 

 32/231 [===>..........................] - ETA: 9s - loss: 0.7483 - accuracy: 0.6318

 33/231 [===>..........................] - ETA: 10s - loss: 0.7549 - accuracy: 0.6354

 41/231 [====>.........................] - ETA: 8s - loss: 0.7824 - accuracy: 0.6509 

 44/231 [====>.........................] - ETA: 8s - loss: 0.7738 - accuracy: 0.6548

 52/231 [=====>........................] - ETA: 6s - loss: 0.7504 - accuracy: 0.6569

 57/231 [======>.......................] - ETA: 6s - loss: 0.7355 - accuracy: 0.6694

 65/231 [=======>......................] - ETA: 5s - loss: 0.7518 - accuracy: 0.6673

 73/231 [========>.....................] - ETA: 4s - loss: 0.7285 - accuracy: 0.6751

 81/231 [=========>....................] - ETA: 4s - loss: 0.7324 - accuracy: 0.6759

 89/231 [==========>...................] - ETA: 3s - loss: 0.7322 - accuracy: 0.6777

 97/231 [===========>..................] - ETA: 3s - loss: 0.7727 - accuracy: 0.6753

105/231 [============>.................] - ETA: 2s - loss: 0.7765 - accuracy: 0.6759

113/231 [=============>................] - ETA: 2s - loss: 0.7752 - accuracy: 0.6764

121/231 [==============>...............] - ETA: 2s - loss: 0.7822 - accuracy: 0.6746

129/231 [===============>..............] - ETA: 2s - loss: 0.7786 - accuracy: 0.6768

137/231 [================>.............] - ETA: 1s - loss: 0.7804 - accuracy: 0.6797

145/231 [=================>............] - ETA: 1s - loss: 0.7711 - accuracy: 0.6802

153/231 [==================>...........] - ETA: 1s - loss: 0.7657 - accuracy: 0.6785

161/231 [===================>..........] - ETA: 1s - loss: 0.7559 - accuracy: 0.6803

169/231 [====================>.........] - ETA: 1s - loss: 0.7543 - accuracy: 0.6788

177/231 [=====================>........] - ETA: 0s - loss: 0.7484 - accuracy: 0.6773

185/231 [=======================>......] - ETA: 0s - loss: 0.7459 - accuracy: 0.6777

193/231 [========================>.....] - ETA: 0s - loss: 0.7415 - accuracy: 0.6767

201/231 [=========================>....] - ETA: 0s - loss: 0.7402 - accuracy: 0.6765

209/231 [==========================>...] - ETA: 0s - loss: 0.7434 - accuracy: 0.6772

217/231 [===========================>..] - ETA: 0s - loss: 0.7366 - accuracy: 0.6768

225/231 [============================>.] - ETA: 0s - loss: 0.7319 - accuracy: 0.6781

231/231 [==============================] - 8s 18ms/step - loss: 0.7295 - accuracy: 0.6794 - val_loss: 0.5710 - val_accuracy: 0.7443


Epoch 2/10


  1/231 [..............................] - ETA: 10s - loss: 0.4422 - accuracy: 0.8438

  9/231 [>.............................] - ETA: 1s - loss: 0.6567 - accuracy: 0.6632 

 17/231 [=>............................] - ETA: 1s - loss: 0.6756 - accuracy: 0.6581

 25/231 [==>...........................] - ETA: 1s - loss: 0.6536 - accuracy: 0.6612

 33/231 [===>..........................] - ETA: 1s - loss: 0.6472 - accuracy: 0.6761

 41/231 [====>.........................] - ETA: 1s - loss: 0.6538 - accuracy: 0.6860

 49/231 [=====>........................] - ETA: 1s - loss: 0.6415 - accuracy: 0.6875

 57/231 [======>.......................] - ETA: 1s - loss: 0.6283 - accuracy: 0.6848

 65/231 [=======>......................] - ETA: 1s - loss: 0.6195 - accuracy: 0.6913

 73/231 [========>.....................] - ETA: 1s - loss: 0.6132 - accuracy: 0.6948

 81/231 [=========>....................] - ETA: 0s - loss: 0.6018 - accuracy: 0.6983

 89/231 [==========>...................] - ETA: 0s - loss: 0.5874 - accuracy: 0.7054

 97/231 [===========>..................] - ETA: 0s - loss: 0.5839 - accuracy: 0.7075

105/231 [============>.................] - ETA: 0s - loss: 0.5846 - accuracy: 0.7065

113/231 [=============>................] - ETA: 0s - loss: 0.5857 - accuracy: 0.7027

121/231 [==============>...............] - ETA: 0s - loss: 0.5813 - accuracy: 0.7064

129/231 [===============>..............] - ETA: 0s - loss: 0.5776 - accuracy: 0.7074

137/231 [================>.............] - ETA: 0s - loss: 0.5755 - accuracy: 0.7069

145/231 [=================>............] - ETA: 0s - loss: 0.5730 - accuracy: 0.7080

153/231 [==================>...........] - ETA: 0s - loss: 0.5681 - accuracy: 0.7106

161/231 [===================>..........] - ETA: 0s - loss: 0.5661 - accuracy: 0.7106

169/231 [====================>.........] - ETA: 0s - loss: 0.5638 - accuracy: 0.7099

177/231 [=====================>........] - ETA: 0s - loss: 0.5627 - accuracy: 0.7115

185/231 [=======================>......] - ETA: 0s - loss: 0.5616 - accuracy: 0.7110

193/231 [========================>.....] - ETA: 0s - loss: 0.5609 - accuracy: 0.7121

201/231 [=========================>....] - ETA: 0s - loss: 0.5615 - accuracy: 0.7121

210/231 [==========================>...] - ETA: 0s - loss: 0.5601 - accuracy: 0.7118

218/231 [===========================>..] - ETA: 0s - loss: 0.5606 - accuracy: 0.7094

227/231 [============================>.] - ETA: 0s - loss: 0.5648 - accuracy: 0.7075

231/231 [==============================] - 2s 8ms/step - loss: 0.5687 - accuracy: 0.7081 - val_loss: 0.6360 - val_accuracy: 0.7329


Epoch 3/10


  1/231 [..............................] - ETA: 10s - loss: 0.4049 - accuracy: 0.7188

  9/231 [>.............................] - ETA: 1s - loss: 0.4965 - accuracy: 0.7431 

 17/231 [=>............................] - ETA: 1s - loss: 0.4874 - accuracy: 0.7316

 25/231 [==>...........................] - ETA: 1s - loss: 0.5452 - accuracy: 0.7088

 33/231 [===>..........................] - ETA: 1s - loss: 0.5315 - accuracy: 0.7197

 41/231 [====>.........................] - ETA: 1s - loss: 0.5319 - accuracy: 0.7218

 49/231 [=====>........................] - ETA: 1s - loss: 0.5370 - accuracy: 0.7054

 57/231 [======>.......................] - ETA: 1s - loss: 0.5355 - accuracy: 0.7116

 65/231 [=======>......................] - ETA: 1s - loss: 0.5401 - accuracy: 0.7178

 73/231 [========>.....................] - ETA: 1s - loss: 0.5364 - accuracy: 0.7183

 82/231 [=========>....................] - ETA: 0s - loss: 0.5301 - accuracy: 0.7210

 90/231 [==========>...................] - ETA: 0s - loss: 0.5284 - accuracy: 0.7229

 98/231 [===========>..................] - ETA: 0s - loss: 0.5306 - accuracy: 0.7223

106/231 [============>.................] - ETA: 0s - loss: 0.5341 - accuracy: 0.7188

114/231 [=============>................] - ETA: 0s - loss: 0.5307 - accuracy: 0.7209

122/231 [==============>...............] - ETA: 0s - loss: 0.5353 - accuracy: 0.7177

130/231 [===============>..............] - ETA: 0s - loss: 0.5315 - accuracy: 0.7197

138/231 [================>.............] - ETA: 0s - loss: 0.5312 - accuracy: 0.7203

146/231 [=================>............] - ETA: 0s - loss: 0.5346 - accuracy: 0.7211

154/231 [===================>..........] - ETA: 0s - loss: 0.5354 - accuracy: 0.7194

162/231 [====================>.........] - ETA: 0s - loss: 0.5327 - accuracy: 0.7201

170/231 [=====================>........] - ETA: 0s - loss: 0.5327 - accuracy: 0.7211

178/231 [======================>.......] - ETA: 0s - loss: 0.5310 - accuracy: 0.7221

186/231 [=======================>......] - ETA: 0s - loss: 0.5308 - accuracy: 0.7221

194/231 [========================>.....] - ETA: 0s - loss: 0.5296 - accuracy: 0.7213

202/231 [=========================>....] - ETA: 0s - loss: 0.5300 - accuracy: 0.7218

210/231 [==========================>...] - ETA: 0s - loss: 0.5282 - accuracy: 0.7220

218/231 [===========================>..] - ETA: 0s - loss: 0.5309 - accuracy: 0.7190

226/231 [============================>.] - ETA: 0s - loss: 0.5313 - accuracy: 0.7176

231/231 [==============================] - 2s 8ms/step - loss: 0.5303 - accuracy: 0.7181 - val_loss: 0.5047 - val_accuracy: 0.7275


Epoch 4/10


  1/231 [..............................] - ETA: 10s - loss: 0.5605 - accuracy: 0.6562

  9/231 [>.............................] - ETA: 1s - loss: 0.5334 - accuracy: 0.6840 

 17/231 [=>............................] - ETA: 1s - loss: 0.5137 - accuracy: 0.7151

 25/231 [==>...........................] - ETA: 1s - loss: 0.4914 - accuracy: 0.7312

 26/231 [==>...........................] - ETA: 2s - loss: 0.4883 - accuracy: 0.7320

 34/231 [===>..........................] - ETA: 2s - loss: 0.4893 - accuracy: 0.7270

 42/231 [====>.........................] - ETA: 1s - loss: 0.4916 - accuracy: 0.7262

 51/231 [=====>........................] - ETA: 1s - loss: 0.4965 - accuracy: 0.7267

 59/231 [======>.......................] - ETA: 1s - loss: 0.4971 - accuracy: 0.7288

 67/231 [=======>......................] - ETA: 1s - loss: 0.4972 - accuracy: 0.7290

 75/231 [========>.....................] - ETA: 1s - loss: 0.4948 - accuracy: 0.7325

 83/231 [=========>....................] - ETA: 1s - loss: 0.4929 - accuracy: 0.7338

 91/231 [==========>...................] - ETA: 1s - loss: 0.4902 - accuracy: 0.7342

 99/231 [===========>..................] - ETA: 1s - loss: 0.4884 - accuracy: 0.7352

107/231 [============>.................] - ETA: 0s - loss: 0.4916 - accuracy: 0.7331

115/231 [=============>................] - ETA: 0s - loss: 0.4938 - accuracy: 0.7288

123/231 [==============>...............] - ETA: 0s - loss: 0.4933 - accuracy: 0.7294

131/231 [================>.............] - ETA: 0s - loss: 0.4903 - accuracy: 0.7338

139/231 [=================>............] - ETA: 0s - loss: 0.4918 - accuracy: 0.7336

147/231 [==================>...........] - ETA: 0s - loss: 0.4951 - accuracy: 0.7326

156/231 [===================>..........] - ETA: 0s - loss: 0.4960 - accuracy: 0.7310

164/231 [====================>.........] - ETA: 0s - loss: 0.4951 - accuracy: 0.7308

172/231 [=====================>........] - ETA: 0s - loss: 0.4948 - accuracy: 0.7335

180/231 [======================>.......] - ETA: 0s - loss: 0.4939 - accuracy: 0.7337

188/231 [=======================>......] - ETA: 0s - loss: 0.4980 - accuracy: 0.7339

197/231 [========================>.....] - ETA: 0s - loss: 0.4989 - accuracy: 0.7329

206/231 [=========================>....] - ETA: 0s - loss: 0.5025 - accuracy: 0.7300

214/231 [==========================>...] - ETA: 0s - loss: 0.5042 - accuracy: 0.7288

223/231 [===========================>..] - ETA: 0s - loss: 0.5048 - accuracy: 0.7304

231/231 [==============================] - ETA: 0s - loss: 0.5037 - accuracy: 0.7303

231/231 [==============================] - 2s 8ms/step - loss: 0.5037 - accuracy: 0.7303 - val_loss: 0.4990 - val_accuracy: 0.7514


Epoch 5/10


  1/231 [..............................] - ETA: 10s - loss: 0.6344 - accuracy: 0.6875

  9/231 [>.............................] - ETA: 1s - loss: 0.4868 - accuracy: 0.7431 

 17/231 [=>............................] - ETA: 1s - loss: 0.5005 - accuracy: 0.7408

 25/231 [==>...........................] - ETA: 1s - loss: 0.4956 - accuracy: 0.7362

 33/231 [===>..........................] - ETA: 1s - loss: 0.5099 - accuracy: 0.7292

 41/231 [====>.........................] - ETA: 1s - loss: 0.5013 - accuracy: 0.7332

 49/231 [=====>........................] - ETA: 1s - loss: 0.5017 - accuracy: 0.7309

 57/231 [======>.......................] - ETA: 1s - loss: 0.4997 - accuracy: 0.7390

 65/231 [=======>......................] - ETA: 1s - loss: 0.5013 - accuracy: 0.7346

 73/231 [========>.....................] - ETA: 1s - loss: 0.4980 - accuracy: 0.7363

 81/231 [=========>....................] - ETA: 0s - loss: 0.4992 - accuracy: 0.7384

 89/231 [==========>...................] - ETA: 0s - loss: 0.5037 - accuracy: 0.7349

 98/231 [===========>..................] - ETA: 0s - loss: 0.5054 - accuracy: 0.7328

107/231 [============>.................] - ETA: 0s - loss: 0.4998 - accuracy: 0.7383

115/231 [=============>................] - ETA: 0s - loss: 0.5052 - accuracy: 0.7367

123/231 [==============>...............] - ETA: 0s - loss: 0.5046 - accuracy: 0.7355

131/231 [================>.............] - ETA: 0s - loss: 0.5044 - accuracy: 0.7323

139/231 [=================>............] - ETA: 0s - loss: 0.5045 - accuracy: 0.7316

147/231 [==================>...........] - ETA: 0s - loss: 0.5031 - accuracy: 0.7313

156/231 [===================>..........] - ETA: 0s - loss: 0.5020 - accuracy: 0.7312

164/231 [====================>.........] - ETA: 0s - loss: 0.5016 - accuracy: 0.7298

173/231 [=====================>........] - ETA: 0s - loss: 0.4987 - accuracy: 0.7323

182/231 [======================>.......] - ETA: 0s - loss: 0.4977 - accuracy: 0.7330

190/231 [=======================>......] - ETA: 0s - loss: 0.4956 - accuracy: 0.7339

198/231 [========================>.....] - ETA: 0s - loss: 0.4959 - accuracy: 0.7339

206/231 [=========================>....] - ETA: 0s - loss: 0.4958 - accuracy: 0.7324

214/231 [==========================>...] - ETA: 0s - loss: 0.4961 - accuracy: 0.7331

222/231 [===========================>..] - ETA: 0s - loss: 0.4968 - accuracy: 0.7325

230/231 [============================>.] - ETA: 0s - loss: 0.4978 - accuracy: 0.7319

231/231 [==============================] - 2s 8ms/step - loss: 0.4980 - accuracy: 0.7320 - val_loss: 0.5052 - val_accuracy: 0.6777


Epoch 6/10


  1/231 [..............................] - ETA: 10s - loss: 0.4737 - accuracy: 0.6250

  9/231 [>.............................] - ETA: 1s - loss: 0.5140 - accuracy: 0.6701 

 17/231 [=>............................] - ETA: 1s - loss: 0.5076 - accuracy: 0.6949

 25/231 [==>...........................] - ETA: 1s - loss: 0.4797 - accuracy: 0.7262

 33/231 [===>..........................] - ETA: 1s - loss: 0.4815 - accuracy: 0.7320

 41/231 [====>.........................] - ETA: 1s - loss: 0.4818 - accuracy: 0.7332

 49/231 [=====>........................] - ETA: 1s - loss: 0.4904 - accuracy: 0.7264

 57/231 [======>.......................] - ETA: 1s - loss: 0.4827 - accuracy: 0.7352

 65/231 [=======>......................] - ETA: 1s - loss: 0.4887 - accuracy: 0.7332

 73/231 [========>.....................] - ETA: 1s - loss: 0.4847 - accuracy: 0.7376

 81/231 [=========>....................] - ETA: 0s - loss: 0.4877 - accuracy: 0.7388

 89/231 [==========>...................] - ETA: 0s - loss: 0.4862 - accuracy: 0.7402

 97/231 [===========>..................] - ETA: 0s - loss: 0.4868 - accuracy: 0.7413

105/231 [============>.................] - ETA: 0s - loss: 0.4910 - accuracy: 0.7357

113/231 [=============>................] - ETA: 0s - loss: 0.4905 - accuracy: 0.7370

121/231 [==============>...............] - ETA: 0s - loss: 0.4918 - accuracy: 0.7384

129/231 [===============>..............] - ETA: 0s - loss: 0.4930 - accuracy: 0.7372

137/231 [================>.............] - ETA: 0s - loss: 0.4920 - accuracy: 0.7370

145/231 [=================>............] - ETA: 0s - loss: 0.4979 - accuracy: 0.7341

153/231 [==================>...........] - ETA: 0s - loss: 0.4957 - accuracy: 0.7349

161/231 [===================>..........] - ETA: 0s - loss: 0.4929 - accuracy: 0.7356

169/231 [====================>.........] - ETA: 0s - loss: 0.4935 - accuracy: 0.7365

177/231 [=====================>........] - ETA: 0s - loss: 0.4962 - accuracy: 0.7368

185/231 [=======================>......] - ETA: 0s - loss: 0.4956 - accuracy: 0.7353

193/231 [========================>.....] - ETA: 0s - loss: 0.4960 - accuracy: 0.7332

202/231 [=========================>....] - ETA: 0s - loss: 0.4972 - accuracy: 0.7331

210/231 [==========================>...] - ETA: 0s - loss: 0.4943 - accuracy: 0.7353

218/231 [===========================>..] - ETA: 0s - loss: 0.4938 - accuracy: 0.7358

226/231 [============================>.] - ETA: 0s - loss: 0.4929 - accuracy: 0.7373

231/231 [==============================] - 2s 8ms/step - loss: 0.4927 - accuracy: 0.7378 - val_loss: 0.4964 - val_accuracy: 0.7210


Epoch 7/10


  1/231 [..............................] - ETA: 10s - loss: 0.4479 - accuracy: 0.7188

  9/231 [>.............................] - ETA: 1s - loss: 0.4321 - accuracy: 0.7639 

 17/231 [=>............................] - ETA: 1s - loss: 0.4283 - accuracy: 0.7665

 26/231 [==>...........................] - ETA: 1s - loss: 0.4355 - accuracy: 0.7620

 34/231 [===>..........................] - ETA: 1s - loss: 0.4500 - accuracy: 0.7555

 43/231 [====>.........................] - ETA: 1s - loss: 0.4467 - accuracy: 0.7558

 51/231 [=====>........................] - ETA: 1s - loss: 0.4526 - accuracy: 0.7543

 59/231 [======>.......................] - ETA: 1s - loss: 0.4619 - accuracy: 0.7532

 67/231 [=======>......................] - ETA: 1s - loss: 0.4668 - accuracy: 0.7472

 76/231 [========>.....................] - ETA: 0s - loss: 0.4753 - accuracy: 0.7401

 84/231 [=========>....................] - ETA: 1s - loss: 0.4762 - accuracy: 0.7411

 92/231 [==========>...................] - ETA: 1s - loss: 0.4799 - accuracy: 0.7385

101/231 [============>.................] - ETA: 1s - loss: 0.4810 - accuracy: 0.7392

110/231 [=============>................] - ETA: 0s - loss: 0.4781 - accuracy: 0.7415

119/231 [==============>...............] - ETA: 0s - loss: 0.4763 - accuracy: 0.7408

127/231 [===============>..............] - ETA: 0s - loss: 0.4754 - accuracy: 0.7399

136/231 [================>.............] - ETA: 0s - loss: 0.4752 - accuracy: 0.7417

145/231 [=================>............] - ETA: 0s - loss: 0.4776 - accuracy: 0.7399

153/231 [==================>...........] - ETA: 0s - loss: 0.4800 - accuracy: 0.7386

162/231 [====================>.........] - ETA: 0s - loss: 0.4806 - accuracy: 0.7392

170/231 [=====================>........] - ETA: 0s - loss: 0.4809 - accuracy: 0.7388

178/231 [======================>.......] - ETA: 0s - loss: 0.4832 - accuracy: 0.7389

187/231 [=======================>......] - ETA: 0s - loss: 0.4838 - accuracy: 0.7386

196/231 [========================>.....] - ETA: 0s - loss: 0.4846 - accuracy: 0.7384

204/231 [=========================>....] - ETA: 0s - loss: 0.4851 - accuracy: 0.7365

212/231 [==========================>...] - ETA: 0s - loss: 0.4836 - accuracy: 0.7381

221/231 [===========================>..] - ETA: 0s - loss: 0.4821 - accuracy: 0.7395

230/231 [============================>.] - ETA: 0s - loss: 0.4836 - accuracy: 0.7399

231/231 [==============================] - 2s 8ms/step - loss: 0.4835 - accuracy: 0.7399 - val_loss: 0.4912 - val_accuracy: 0.7438


Epoch 8/10


  1/231 [..............................] - ETA: 9s - loss: 0.4874 - accuracy: 0.6250

 10/231 [>.............................] - ETA: 1s - loss: 0.4741 - accuracy: 0.7312

 18/231 [=>............................] - ETA: 1s - loss: 0.5010 - accuracy: 0.7274

 27/231 [==>...........................] - ETA: 1s - loss: 0.4880 - accuracy: 0.7315

 35/231 [===>..........................] - ETA: 1s - loss: 0.4752 - accuracy: 0.7375

 44/231 [====>.........................] - ETA: 1s - loss: 0.4792 - accuracy: 0.7422

 53/231 [=====>........................] - ETA: 1s - loss: 0.4784 - accuracy: 0.7435

 62/231 [=======>......................] - ETA: 1s - loss: 0.4742 - accuracy: 0.7455

 70/231 [========>.....................] - ETA: 1s - loss: 0.4720 - accuracy: 0.7473

 78/231 [=========>....................] - ETA: 0s - loss: 0.4715 - accuracy: 0.7456

 86/231 [==========>...................] - ETA: 0s - loss: 0.4726 - accuracy: 0.7475

 94/231 [===========>..................] - ETA: 0s - loss: 0.4754 - accuracy: 0.7460

103/231 [============>.................] - ETA: 0s - loss: 0.4758 - accuracy: 0.7430

112/231 [=============>................] - ETA: 0s - loss: 0.4782 - accuracy: 0.7427

121/231 [==============>...............] - ETA: 0s - loss: 0.4744 - accuracy: 0.7451

130/231 [===============>..............] - ETA: 0s - loss: 0.4759 - accuracy: 0.7435

139/231 [=================>............] - ETA: 0s - loss: 0.4756 - accuracy: 0.7469

147/231 [==================>...........] - ETA: 0s - loss: 0.4757 - accuracy: 0.7445

155/231 [===================>..........] - ETA: 0s - loss: 0.4764 - accuracy: 0.7437

164/231 [====================>.........] - ETA: 0s - loss: 0.4762 - accuracy: 0.7441

173/231 [=====================>........] - ETA: 0s - loss: 0.4747 - accuracy: 0.7437

182/231 [======================>.......] - ETA: 0s - loss: 0.4741 - accuracy: 0.7448

190/231 [=======================>......] - ETA: 0s - loss: 0.4773 - accuracy: 0.7423

199/231 [========================>.....] - ETA: 0s - loss: 0.4758 - accuracy: 0.7426

208/231 [==========================>...] - ETA: 0s - loss: 0.4756 - accuracy: 0.7428

217/231 [===========================>..] - ETA: 0s - loss: 0.4765 - accuracy: 0.7424

225/231 [============================>.] - ETA: 0s - loss: 0.4778 - accuracy: 0.7415

231/231 [==============================] - 2s 7ms/step - loss: 0.4775 - accuracy: 0.7417 - val_loss: 0.4991 - val_accuracy: 0.7178


Epoch 9/10


  1/231 [..............................] - ETA: 10s - loss: 0.4264 - accuracy: 0.8125

  9/231 [>.............................] - ETA: 1s - loss: 0.5062 - accuracy: 0.7257 

 18/231 [=>............................] - ETA: 1s - loss: 0.5177 - accuracy: 0.7118

 27/231 [==>...........................] - ETA: 1s - loss: 0.5006 - accuracy: 0.7211

 35/231 [===>..........................] - ETA: 1s - loss: 0.4877 - accuracy: 0.7277

 44/231 [====>.........................] - ETA: 1s - loss: 0.4884 - accuracy: 0.7273

 52/231 [=====>........................] - ETA: 1s - loss: 0.4889 - accuracy: 0.7290

 61/231 [======>.......................] - ETA: 1s - loss: 0.4837 - accuracy: 0.7346

 69/231 [=======>......................] - ETA: 1s - loss: 0.4777 - accuracy: 0.7391

 77/231 [=========>....................] - ETA: 0s - loss: 0.4769 - accuracy: 0.7419

 86/231 [==========>...................] - ETA: 0s - loss: 0.4769 - accuracy: 0.7424

 94/231 [===========>..................] - ETA: 0s - loss: 0.4773 - accuracy: 0.7410

103/231 [============>.................] - ETA: 0s - loss: 0.4770 - accuracy: 0.7385

112/231 [=============>................] - ETA: 0s - loss: 0.4819 - accuracy: 0.7366

120/231 [==============>...............] - ETA: 0s - loss: 0.4796 - accuracy: 0.7357

128/231 [===============>..............] - ETA: 0s - loss: 0.4778 - accuracy: 0.7405

137/231 [================>.............] - ETA: 0s - loss: 0.4740 - accuracy: 0.7425

146/231 [=================>............] - ETA: 0s - loss: 0.4765 - accuracy: 0.7393

155/231 [===================>..........] - ETA: 0s - loss: 0.4742 - accuracy: 0.7415

164/231 [====================>.........] - ETA: 0s - loss: 0.4756 - accuracy: 0.7431

173/231 [=====================>........] - ETA: 0s - loss: 0.4754 - accuracy: 0.7421

182/231 [======================>.......] - ETA: 0s - loss: 0.4735 - accuracy: 0.7424

190/231 [=======================>......] - ETA: 0s - loss: 0.4733 - accuracy: 0.7434

198/231 [========================>.....] - ETA: 0s - loss: 0.4730 - accuracy: 0.7449

206/231 [=========================>....] - ETA: 0s - loss: 0.4720 - accuracy: 0.7445

215/231 [==========================>...] - ETA: 0s - loss: 0.4739 - accuracy: 0.7432

224/231 [============================>.] - ETA: 0s - loss: 0.4731 - accuracy: 0.7432

231/231 [==============================] - 2s 7ms/step - loss: 0.4719 - accuracy: 0.7440 - val_loss: 0.4956 - val_accuracy: 0.7205


Epoch 10/10


  1/231 [..............................] - ETA: 9s - loss: 0.4019 - accuracy: 0.7812

  9/231 [>.............................] - ETA: 1s - loss: 0.4144 - accuracy: 0.7639

 17/231 [=>............................] - ETA: 1s - loss: 0.4381 - accuracy: 0.7335

 26/231 [==>...........................] - ETA: 1s - loss: 0.4374 - accuracy: 0.7548

 34/231 [===>..........................] - ETA: 1s - loss: 0.4390 - accuracy: 0.7647

 42/231 [====>.........................] - ETA: 1s - loss: 0.4434 - accuracy: 0.7656

 50/231 [=====>........................] - ETA: 1s - loss: 0.4567 - accuracy: 0.7563

 58/231 [======>.......................] - ETA: 1s - loss: 0.4603 - accuracy: 0.7559

 66/231 [=======>......................] - ETA: 1s - loss: 0.4636 - accuracy: 0.7505

 74/231 [========>.....................] - ETA: 0s - loss: 0.4602 - accuracy: 0.7521

 82/231 [=========>....................] - ETA: 0s - loss: 0.4589 - accuracy: 0.7489

 91/231 [==========>...................] - ETA: 0s - loss: 0.4533 - accuracy: 0.7541

 99/231 [===========>..................] - ETA: 0s - loss: 0.4541 - accuracy: 0.7538

107/231 [============>.................] - ETA: 0s - loss: 0.4531 - accuracy: 0.7585

115/231 [=============>................] - ETA: 0s - loss: 0.4543 - accuracy: 0.7590

124/231 [===============>..............] - ETA: 0s - loss: 0.4522 - accuracy: 0.7598

132/231 [================>.............] - ETA: 0s - loss: 0.4572 - accuracy: 0.7597

140/231 [=================>............] - ETA: 0s - loss: 0.4625 - accuracy: 0.7538

149/231 [==================>...........] - ETA: 0s - loss: 0.4641 - accuracy: 0.7519

158/231 [===================>..........] - ETA: 0s - loss: 0.4658 - accuracy: 0.7516

167/231 [====================>.........] - ETA: 0s - loss: 0.4652 - accuracy: 0.7521

176/231 [=====================>........] - ETA: 0s - loss: 0.4645 - accuracy: 0.7509

184/231 [======================>.......] - ETA: 0s - loss: 0.4657 - accuracy: 0.7498

193/231 [========================>.....] - ETA: 0s - loss: 0.4656 - accuracy: 0.7505

202/231 [=========================>....] - ETA: 0s - loss: 0.4659 - accuracy: 0.7506

211/231 [==========================>...] - ETA: 0s - loss: 0.4651 - accuracy: 0.7512

220/231 [===========================>..] - ETA: 0s - loss: 0.4653 - accuracy: 0.7523

229/231 [============================>.] - ETA: 0s - loss: 0.4670 - accuracy: 0.7519

231/231 [==============================] - 2s 7ms/step - loss: 0.4669 - accuracy: 0.7519 - val_loss: 0.5177 - val_accuracy: 0.6907


In [27]:
loss, accuracy = model.evaluate(test_ds)
print("Accuracy", accuracy)

 1/73 [..............................] - ETA: 1s - loss: 0.5921 - accuracy: 0.5938

12/73 [===>..........................] - ETA: 0s - loss: 0.4952 - accuracy: 0.7161

23/73 [========>.....................] - ETA: 0s - loss: 0.4948 - accuracy: 0.7215

34/73 [============>.................] - ETA: 0s - loss: 0.4968 - accuracy: 0.7178

45/73 [=================>............] - ETA: 0s - loss: 0.4987 - accuracy: 0.7104

56/73 [======================>.......] - ETA: 0s - loss: 0.5129 - accuracy: 0.7031

67/73 [==========================>...] - ETA: 0s - loss: 0.5183 - accuracy: 0.7020

73/73 [==============================] - 0s 5ms/step - loss: 0.5207 - accuracy: 0.7015


Accuracy 0.7014731168746948


Key point: You will typically see best results with deep learning with much larger and more complex datasets. When working with a small dataset like this one, we recommend using a decision tree or random forest as a strong baseline. The goal of this tutorial is not to train an accurate model, but to demonstrate the mechanics of working with structured data, so you have code to use as a starting point when working with your own datasets in the future.

## Next steps
The best way to learn more about classifying structured data is to try it yourself. We suggest finding another dataset to work with, and training a model to classify it using code similar to the above. To improve accuracy, think carefully about which features to include in your model, and how they should be represented.